### ISSUE TITLE
Problems downloading the results

### ISSUE THREAD

**Issue by fernangomezv** [digitalcytometry/ecotyper#64] opened 2023-06-02 19:00 UTC
Hello to everyone, and thanks for your fantastic platform!

I have problems when I'm trying to download my analysis results (after assigned cell states and ecotypes).
The button "Download Results" doesn't work.

I really appreciate any help you can provide.

**Comment by BALuca** [comment] 2023-06-05 10:35
Hi,

Apologize for the problems. There might have been a problem with the web server. We believe that the issue is fixed now. If you are still encountering problems please send us a reproducible example and we will investigate the issue further.

Best regards,
The EcoTyper team

**Closed** 2023-06-05 12:49 UTC
